### ISSUE TITLE
Ginkgo progress report will panic with a gomega.Consistently ShouldNot(HaveOccurred())

### ISSUE THREAD

**Issue by bobbypage** [onsi/ginkgo#1150]
Hi all,

I have been looking at adding progress reports (really cool feature) into some of k8s e2e tests. I ran into a problem with the progress reports sometimes resulting in a panic. 

This was reproduced on ginkgo 2.8.4 and gomega 1.27.1.

I put together a simple test that can reproduce this:

```
package books_test

import (
	"context"
	"time"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("Book", func() {
	Context("some context", func() {
		It("some it block", func(ctx context.Context) {
			By("Starting the Consistently")

			Consistently(ctx, func(ctx context.Context) error {
				By("inside the gomega Consistently")
				time.Sleep(2 * time.Second)
				return nil
			}, time.Second*30, time.Second*5).ShouldNot(HaveOccurred())
		})
	})

})
```

Running this with `$ ginkgo -v` results in the test passing:

```
$ ginkgo -v
Running Suite: Books Suite - /tmp/ginkgorepro/books
===================================================
Random Seed: 1677545264

Will run 1 of 1 specs
------------------------------
Book some context some it block
/tmp/ginkgorepro/books/book_test.go:13
  STEP: Starting the Consistently @ 02/27/23 16:47:45.13
  STEP: inside the gomega Consistently @ 02/27/23 16:47:45.131
  STEP: inside the gomega Consistently @ 02/27/23 16:47:52.134
  STEP: inside the gomega Consistently @ 02/27/23 16:47:59.139
  STEP: inside the gomega Consistently @ 02/27/23 16:48:06.143
  STEP: inside the gomega Consistently @ 02/27/23 16:48:13.146
• [30.017 seconds]
------------------------------

Ran 1 of 1 Specs in 30.017 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS

Ginkgo ran 1 suite in 30.77264307s
Test Suite Passed
```

but If I ran it with `--poll-progress` flags, it will panic:

```
$ ginkgo -v --poll-progress-after=2s --poll-progress-interval=2s
Running Suite: Books Suite - /tmp/ginkgorepro/books
===================================================
Random Seed: 1677545333

Will run 1 of 1 specs
------------------------------
Book some context some it block
/tmp/ginkgorepro/books/book_test.go:13
  STEP: Starting the Consistently @ 02/27/23 16:48:53.96
  STEP: inside the gomega Consistently @ 02/27/23 16:48:53.96
--- FAIL: TestBooks (2.00s)
panic: interface conversion: interface is nil, not error [recovered]
        panic: interface conversion: interface is nil, not error

goroutine 6 [running]:
testing.tRunner.func1.2({0x7a4ce0, 0xc00028a000})
        /usr/local/google/home/porterdavid/.gimme/versions/go1.20.1.linux.amd64/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
        /usr/local/google/home/porterdavid/.gimme/versions/go1.20.1.linux.amd64/src/testing/testing.go:1529 +0x39f
panic({0x7a4ce0, 0xc00028a000})
        /usr/local/google/home/porterdavid/.gimme/versions/go1.20.1.linux.amd64/src/runtime/panic.go:884 +0x213
github.com/onsi/gomega/matchers.(*HaveOccurredMatcher).NegatedFailureMessage(0xc00015cf58?, {0x0?, 0x0})
        /usr/local/google/home/porterdavid/go/pkg/mod/github.com/onsi/gomega@v1.27.1/matchers/have_occurred_matcher.go:34 +0x66
github.com/onsi/gomega/internal.(*AsyncAssertion).match.func2()
        /usr/local/google/home/porterdavid/go/pkg/mod/github.com/onsi/gomega@v1.27.1/internal/async_assertion.go:431 +0x1c9
github.com/onsi/ginkgo/v2/internal.(*specContext).QueryProgressReporters(0xc00014c080)
        /usr/local/google/home/porterdavid/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.8.4/internal/spec_context.go:87 +0x2dc
github.com/onsi/ginkgo/v2/internal.(*Suite).generateProgressReport(_, _)
        /usr/local/google/home/porterdavid/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.8.4/internal/suite.go:343 +0x167
github.com/onsi/ginkgo/v2/internal.(*Suite).runNode(_, {0x3, 0x4, {0x80ca5c, 0xd}, 0xc000075e30, {{0x935323, 0x23}, 0xd, {0x0, ...}, ...}, ...}, ...)
        /usr/local/google/home/porterdavid/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.8.4/internal/suite.go:973 +0x164c
github.com/onsi/ginkgo/v2/internal.(*group).attemptSpec(0xc000164ff8, 0x1, {{0xc0000fb500?, 0xc000142000?, 0x2?}, 0x0?})
        /usr/local/google/home/porterdavid/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.8.4/internal/group.go:199 +0xbc5
github.com/onsi/ginkgo/v2/internal.(*group).run(0xc000164ff8, {0xc00013c000?, 0x0?, 0x0?})
        /usr/local/google/home/porterdavid/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.8.4/internal/group.go:346 +0x8e5
github.com/onsi/ginkgo/v2/internal.(*Suite).runSpecs(0xc0000d6a80, {0x80abf1, 0xb}, {0xb45340, 0x0, 0x0}, {0xc00002a104, 0x16}, 0x0, {0xc00007ec80, ...})
        /usr/local/google/home/porterdavid/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.8.4/internal/suite.go:454 +0xabb
github.com/onsi/ginkgo/v2/internal.(*Suite).Run(_, {_, _}, {_, _, _}, {_, _}, _, {0x8b9570, ...}, ...)
        /usr/local/google/home/porterdavid/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.8.4/internal/suite.go:110 +0x435
github.com/onsi/ginkgo/v2.RunSpecs({0x8b4ea0, 0xc0000c1860}, {0x80abf1, 0xb}, {0x0?, 0x0, 0x0?})
        /usr/local/google/home/porterdavid/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.8.4/core_dsl.go:319 +0xfb7
github.com/bobbypage/ginkgorepro/books_test.TestBooks(0x0?)
        /tmp/ginkgorepro/books/books_suite_test.go:12 +0x4a
testing.tRunner(0xc0000c1860, 0x848058)
        /usr/local/google/home/porterdavid/.gimme/versions/go1.20.1.linux.amd64/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
        /usr/local/google/home/porterdavid/.gimme/versions/go1.20.1.linux.amd64/src/testing/testing.go:1629 +0x3ea

Ginkgo ran 1 suite in 2.680089428s

Test Suite Failed
```

**Comment by bobbypage** [comment]
It seems like this matcher https://github.com/onsi/gomega/blob/a84e3403e8738c03d8fe9c8f312443574ab86c91/matchers/have_occurred_matcher.go#L34 is being passed `nil` here as `actual` and then type casting it to an error which is resulting in the panic

**Comment by onsi** [comment]
thanks for reporting this @bobbypage  - and for taking the time to put together a reproducer!  it is, in fact, what you're pointing to.  prior to the polling progress reports it would have been impossible for `NegatedFailureMessage` to get called without an error (since the `NegatedFailureMessage` is only called when `ShouldNot(HaveOccurred())` **fails** there must, necessarily, be an error that has occured).  The combination of polling progress and `Consistently` breaks this assumption.

I'll push a fix out momentarily.

**Comment by bobbypage** [comment]
Thank you @onsi for the quick response and explanation, that makes sense!

**Comment by onsi** [comment]
durp - actually this is a bit more subtle than that.  I think the correct design here is for `Consistently` to simply report that all remains well (since the match is good netiher the `FailureMessage` nor the `NegatedFailureMessage` will be relevant and could be confusing if printed out).  will need to think on it... so by "momentarily" I think I actually mean "tomorrow"

**Comment by bobbypage** [comment]
Yeah, I was looking into it, it seems in this case when the progress report is polled the Consistently is expecting to get back to nil, but is not (e.g. in the example, it is blocked on the sleep). So to convey that info, maybe it makes sense to handle that as special case in the failure text?

```
func (matcher *HaveOccurredMatcher) NegatedFailureMessage(actual interface{}) (message string) {
	if actual == nil {
		return fmt.Sprintf("nil error was not returned as expected")
	}
	return fmt.Sprintf("Unexpected error:\n%s\n%s\n%s", format.Object(actual, 1), format.IndentString(actual.(error).Error(), 1), "occurred")
}
```

**Comment by onsi** [comment]
actually, this wasn't so tricky after all.  it's now fixed over on Gomega as of commit 28a319b0172d9e7d062584af203aa3ef562d05ae

if you'd be up for pulling that sha and playing with it a bit - I'd appreciate feedback on the experience and message that it gives you (you can just rerun your reproducer and should see it work)

**Comment by bobbypage** [comment]
Thanks for the super quick fix, here's what it looks like with the reproducer:

```
  ------------------------------
  STEP: inside the gomega Consistently @ 02/27/23 19:08:23.688
  ------------------------------
  Automatically polling progress:
    Book some context some it block (Spec Runtime: 28.03s)
      /tmp/ginkgorepro/books/book_test.go:13
      In [It] (Node Runtime: 28.03s)
        /tmp/ginkgorepro/books/book_test.go:13
        At [By Step] inside the gomega Consistently (Step Runtime: 23ms)
          /tmp/ginkgorepro/books/book_test.go:17

        Spec Goroutine
        goroutine 24 [sleep]
          time.Sleep(0x77359400)
            /usr/local/google/home/porterdavid/.gimme/versions/go1.20.1.linux.amd64/src/runtime/time.go:195
        > github.com/bobbypage/ginkgorepro/books_test.glob..func1.1.1.1({0x7f3ae4c06fb8, 0xc0001b8f40})
            /tmp/ginkgorepro/books/book_test.go:18
              | Consistently(ctx, func(ctx context.Context) error {
              |         By("inside the gomega Consistently")
              >         time.Sleep(2 * time.Second)
              |         return nil
              | }, time.Second*30, time.Second*5).ShouldNot(HaveOccurred())
          reflect.Value.call({0x97ae20, 0xa37018, 0x13}, {0x9f2fd5, 0x4}, {0xc0001369c0, 0x1, 0x1})
            /usr/local/google/home/porterdavid/.gimme/versions/go1.20.1.linux.amd64/src/reflect/value.go:586
          reflect.Value.Call({0x97ae20, 0xa37018, 0x13}, {0xc0001369c0, 0x1, 0x1})
            /usr/local/google/home/porterdavid/.gimme/versions/go1.20.1.linux.amd64/src/reflect/value.go:370
          github.com/onsi/gomega/internal.(*AsyncAssertion).buildActualPoller.func3()
            /usr/local/google/home/porterdavid/gohack/github.com/onsi/gomega/internal/async_assertion.go:325
          github.com/onsi/gomega/internal.(*AsyncAssertion).match(0xc00022d490, {0xa69aa0, 0xcecef0}, 0x0, {0x0, 0x0, 0x0})
            /usr/local/google/home/porterdavid/gohack/github.com/onsi/gomega/internal/async_assertion.go:540
          github.com/onsi/gomega/internal.(*AsyncAssertion).ShouldNot(0xc00022d490, {0xa69aa0, 0xcecef0}, {0x0, 0x0, 0x0})
            /usr/local/google/home/porterdavid/gohack/github.com/onsi/gomega/internal/async_assertion.go:151
        > github.com/bobbypage/ginkgorepro/books_test.glob..func1.1.1({0x7f3ae4c06fb8, 0xc0001b8f40})
            /tmp/ginkgorepro/books/book_test.go:20
              |                         time.Sleep(2 * time.Second)
              |                         return nil
              >                 }, time.Second*30, time.Second*5).ShouldNot(HaveOccurred())
              |         })
              | })
          github.com/onsi/ginkgo/v2/internal.extractBodyFunction.func2({0xa6ac50, 0xc0001b8f40})
            /usr/local/google/home/porterdavid/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.8.4/internal/node.go:456
          github.com/onsi/ginkgo/v2/internal.(*Suite).runNode.func3()
            /usr/local/google/home/porterdavid/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.8.4/internal/suite.go:854
          github.com/onsi/ginkgo/v2/internal.(*Suite).runNode
            /usr/local/google/home/porterdavid/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.8.4/internal/suite.go:841

        Begin Additional Progress Reports >>
          There is no failure as the matcher passed to Consistently has not yet failed
        << End Additional Progress Reports
  ------------------------------
• [30.008 seconds]
------------------------------

Ran 1 of 1 Specs in 30.008 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
```

**Comment by onsi** [comment]
great! i just pushed out gomega 1.27.2 which includes this

**Comment by aojea** [comment]
it is a privilege of kubernetes have golden support from ginkgo ;)

**Comment by onsi** [comment]
happy to help and grateful for the feedback and brainstorming 😄
