### ISSUE TITLE
handle SIGQUIT gooder

### ISSUE THREAD

**Issue by vito** [onsi/ginkgo#134]
pls

```
•••••••••^\SIGQUIT: quit
PC=0x40e43

goroutine 0 [idle]:
runtime.mach_semaphore_timedwait(0x1517f00001a03, 0xc23b9a6d81, 0x7fff5fbff4fc, 0x1517f, 0x369d6, 0x3b9a6d8108012000, 0xc208012000, 0x3dfb8, 0x34300, 0x750710, ...)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/sys_darwin_amd64.s:422 +0x13
semasleep()
	/usr/local/Cellar/go/1.4/libexec/src/runtime/os_darwin.c:428 +0xe4
runtime.onM(0x750710)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/asm_amd64.s:257 +0x68
runtime.mstart()
	/usr/local/Cellar/go/1.4/libexec/src/runtime/proc.c:818

goroutine 6 [syscall]:
runtime.notetsleepg(0x7501d8, 0x4e94914ea381, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/lock_sema.go:266 +0x8c fp=0xc208018768 sp=0xc208018728
runtime.timerproc()
	/usr/local/Cellar/go/1.4/libexec/src/runtime/time.go:207 +0xfa fp=0xc2080187e0 sp=0xc208018768
runtime.goexit()
	/usr/local/Cellar/go/1.4/libexec/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080187e8 sp=0xc2080187e0
created by SIGQUIT: quitruntime.addtimerLocked

PC=	0x3bea3/usr/local/Cellar/go/1.4/libexec/src/runtime/time.go
:
113 +goroutine 0x1ba17
 [
syscallgoroutine ]:
1 [chan receive]:
runtime.notetsleepg(0x799f60, 0xdf8475800)
testing.RunTests(0x5d7518, 	0x7482d0/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/lock_sema.c, :0x1263,  +0x10x71,  fp=0x5d74010x799f38)
 sp=0x799f08
	/usr/local/Cellar/go/1.4/libexec/src/testing/testing.go:runtime.MHeap_Scavenger556( +)
0xad6
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/mheap.ctesting.(*M).Run:(5320xc208041360 +, 0xa30x758300 fp=)
0x799fa8	 sp=/usr/local/Cellar/go/1.4/libexec/src/testing/testing.go:0x799f38485 +
0x6c
runtime.goexit()
main.main	(/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/proc.c)
:1445	 fp=github.com/cloudfoundry-incubator/rep/snapshot/_test/_testmain.go0x799fb0: sp=540x799fa8 +
0x1d5
created by runtime.main
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/proc.c
:207goroutine
5
 [goroutine syscall16]:
 [syscall]:
os/signal.loopsyscall.Syscall6(()
0x7, 0x2000, 0x77b504, 0x0, 0xc208048120	, /usr/local/Cellar/go/1.4/libexec/src/os/signal/signal_unix.go0x0:, 210x0 +, 0x1f0x2b5d9
, 0x60, created by 0xc208048120os/signal.init·1)

	/usr/local/Cellar/go/1.4/libexec/src/os/signal/signal_unix.go	:/usr/local/Cellar/go/1.3.3/libexec/src/pkg/syscall/asm_darwin_amd64.s27: +440x35 +
0x5

goroutine 7 [syscall.wait4running(]:
0x2000, 	goroutine running on other thread; stack unavailable
0x77b504, 0x0created by , 0xc208048120testing.RunTests,
0x3355b, 0x0, 	0x0/usr/local/Cellar/go/1.4/libexec/src/testing/testing.go)
:	555/usr/local/Cellar/go/1.3.3/libexec/src/pkg/syscall/zsyscall_darwin_amd64.go:32 +0x7d
 +syscall.Wait4(0xa8b0x2000
,
0x77b54cgoroutine , 80x0 [, chan receive0xc208048120]:
, 0xc20800e0c0, 0x0, 0x0)
	github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).registerForInterrupts/usr/local/Cellar/go/1.3.3/libexec/src/pkg/syscall/syscall_bsd.go(:0xc2080c7440129)
 +0x64
os.(*Process).wait(0xc20800e0c0	, /Users/pivotal/workspace/diego-release/src/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go0x0:, 1750x0 +, 0x10d0x0
)
created by github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run
/usr/local/Cellar/go/1.3.3/libexec/src/pkg/os/exec_unix.go	:/Users/pivotal/workspace/diego-release/src/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go22: +560xfe +
0x5f
os.(*Process).Wait
(goroutine 0xc20800e0c09,  [0x0select, ]:
0x0, 0x0)
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/os/doc.go:45 +github.com/cloudfoundry/gunk/workpool.worker0x39(
0xc208159b60, os/exec.(*Cmd).Wait0xc20803dce0()
0xc20804ab40, 	0x0/Users/pivotal/workspace/diego-release/src/github.com/cloudfoundry/gunk/workpool/workpool.go:71 +0x151
created by github.com/cloudfoundry/gunk/workpool.New,
	/Users/pivotal/workspace/diego-release/src/github.com/cloudfoundry/gunk/workpool/workpool.go:0x044)
 +0x189
/usr/local/Cellar/go/1.3.3/libexec/src/pkg/os/exec/exec.go
:goroutine 35710 + [0x1dbselect
]:
github.com/onsi/ginkgo/ginkgo/testrunner.(*TestRunner).run(github.com/cloudfoundry/gunk/workpool.worker0xc208062e70(, 0xc208159b600xc20804ab40, , 0xc20803dce00x0)
, 0x0	)
/Users/pivotal/workspace/diego-release/src/github.com/cloudfoundry/gunk/workpool/workpool.go:	71/Users/pivotal/workspace/diego-release/src/github.com/onsi/ginkgo/ginkgo/testrunner/test_runner.go +:0x151330
 +0x1cfcreated by
github.com/cloudfoundry/gunk/workpool.New
github.com/onsi/ginkgo/ginkgo/testrunner.(*TestRunner).runSerialGinkgoSuite	(/Users/pivotal/workspace/diego-release/src/github.com/cloudfoundry/gunk/workpool/workpool.go0xc208062e70:, 440x0 +)
0x189
/Users/pivotal/workspace/diego-release/src/github.com/onsi/ginkgo/ginkgo/testrunner/test_runner.go
:147goroutine  +110x148 [
select]:
github.com/onsi/ginkgo/ginkgo/testrunner.(*TestRunner).Run(0xc208062e70, 0xc208060000github.com/cloudfoundry/gunk/workpool.worker)
(	0xc208159b60/Users/pivotal/workspace/diego-release/src/github.com/onsi/ginkgo/ginkgo/testrunner/test_runner.go, :0xc20803dce0126)
 +0x9d
/Users/pivotal/workspace/diego-release/src/github.com/cloudfoundry/gunk/workpool/workpool.go:main.(*SuiteRunner).RunSuites71( +0xc208038b600x151,
0xc20803e0e8, created by 0x1github.com/cloudfoundry/gunk/workpool.New,
0x1, 	0x8/Users/pivotal/workspace/diego-release/src/github.com/cloudfoundry/gunk/workpool/workpool.go, :0x044,  +0x00x189,
0x0
, goroutine 0x112)
 [	select/Users/pivotal/workspace/diego-release/src/github.com/onsi/ginkgo/ginkgo/suite_runner.go]:
:87 +0x645
github.com/cloudfoundry/gunk/workpool.workermain.(*SpecRunner).RunSpecs((0xc208159b600xc20800e740, , 0xc20803dce00xc208038d50)
, 0x0	, /Users/pivotal/workspace/diego-release/src/github.com/cloudfoundry/gunk/workpool/workpool.go0x0:, 710x672610 +, 0x1510x0
, 0x0)
created by github.com/cloudfoundry/gunk/workpool.New
	/Users/pivotal/workspace/diego-release/src/github.com/onsi/ginkgo/ginkgo/run_command.go	:/Users/pivotal/workspace/diego-release/src/github.com/cloudfoundry/gunk/workpool/workpool.go99: +440xf1d +
0x189
main.*SpecRunner.RunSpecs·fm
(goroutine 0xc208038d5013,  [0x0select, ]:
0x0, 0x672610, 0x0github.com/cloudfoundry/gunk/workpool.worker, (0x00xc208159b60)
, 	0xc20803dce0/Users/pivotal/workspace/diego-release/src/github.com/onsi/ginkgo/ginkgo/run_command.go)
:35	 +/Users/pivotal/workspace/diego-release/src/github.com/cloudfoundry/gunk/workpool/workpool.go0x62:
71 +main.(*Command).Run0x151(
0xc20804e500, created by 0xc208038d40github.com/cloudfoundry/gunk/workpool.New,
0x1	, /Users/pivotal/workspace/diego-release/src/github.com/cloudfoundry/gunk/workpool/workpool.go0x1:, 440x672610 +, 0x1890x0
,
0x0goroutine )
14	 [/Users/pivotal/workspace/diego-release/src/github.com/onsi/ginkgo/ginkgo/main.go:153 +0xb0
main.main()
select	/Users/pivotal/workspace/diego-release/src/github.com/onsi/ginkgo/ginkgo/main.go:201 +]:
0x310

goroutine github.com/cloudfoundry/gunk/workpool.worker19( [0xc208159b60finalizer wait, ]:
0xc20803dce0)
	/Users/pivotal/workspace/diego-release/src/github.com/cloudfoundry/gunk/workpool/workpool.goruntime.park:(710x22a20 +, 0x1510x671950
, 0x6703e9created by )
github.com/cloudfoundry/gunk/workpool.New
/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/proc.c	:/Users/pivotal/workspace/diego-release/src/github.com/cloudfoundry/gunk/workpool/workpool.go1369: +440x89 +
0x189runtime.parkunlock
(
0x671950goroutine , 150x6703e9 [)
select	]:
/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/proc.c:1385 +github.com/cloudfoundry/gunk/workpool.worker0x3b(
0xc208159b60runfinq, (0xc20803dce0)
)
		/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/mgc0.c/Users/pivotal/workspace/diego-release/src/github.com/cloudfoundry/gunk/workpool/workpool.go:71 +0x151
created by github.com/cloudfoundry/gunk/workpool.New
	/Users/pivotal/workspace/diego-release/src/github.com/cloudfoundry/gunk/workpool/workpool.go::44 +0x189
2644
 +goroutine 0xcf16
 [selectruntime.goexit]:
()
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/proc.cgithub.com/cloudfoundry/gunk/workpool.worker:(14450xc208159b60
, 0xc20803dce0)

	goroutine /Users/pivotal/workspace/diego-release/src/github.com/cloudfoundry/gunk/workpool/workpool.go20: [71syscall +]:
0x151
created by github.com/cloudfoundry/gunk/workpool.New
os/signal.loop	(/Users/pivotal/workspace/diego-release/src/github.com/cloudfoundry/gunk/workpool/workpool.go)
:	44/usr/local/Cellar/go/1.3.3/libexec/src/pkg/os/signal/signal_unix.go +:0x18921
 +
0x1egoroutine
17 [created by selectos/signal.init·1]:

	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/os/signal/signal_unix.go:github.com/cloudfoundry/gunk/workpool.worker27( +0xc208159b600x32,
0xc20803dce0
)
goroutine 	21/Users/pivotal/workspace/diego-release/src/github.com/cloudfoundry/gunk/workpool/workpool.go [:71 +chan receive0x151]:

created by github.com/cloudfoundry/gunk/workpool.New
	/Users/pivotal/workspace/diego-release/src/github.com/cloudfoundry/gunk/workpool/workpool.go:main.(*InterruptHandler).handleInterrupt44( +0xc20800e7200x189)


	goroutine /Users/pivotal/workspace/diego-release/src/github.com/onsi/ginkgo/ginkgo/interrupt_handler.go18: [select37]:
 +0xbf
github.com/cloudfoundry/gunk/workpool.worker(0xc208159b60created by , main.NewInterruptHandler0xc20803dce0
)
		/Users/pivotal/workspace/diego-release/src/github.com/onsi/ginkgo/ginkgo/interrupt_handler.go/Users/pivotal/workspace/diego-release/src/github.com/cloudfoundry/gunk/workpool/workpool.go::2171 + +0xa00x151


created by github.com/cloudfoundry/gunk/workpool.Newgoroutine
22	 [/Users/pivotal/workspace/diego-release/src/github.com/cloudfoundry/gunk/workpool/workpool.gochan receive:]:
44 +0x189

main.(*InterruptHandler).handleInterruptrax     (0xe
0xc20800e760)
	/Users/pivotal/workspace/diego-release/src/github.com/onsi/ginkgo/ginkgo/interrupt_handler.go:37rbx      +0xbf
0x3b9a6d81created by
main.NewInterruptHandler
rcx     	0x7fff5fbff4c8/Users/pivotal/workspace/diego-release/src/github.com/onsi/ginkgo/ginkgo/interrupt_handler.go
:rdx     210x3b9a6d81 +
0xa0rdi
0x1a03

goroutine rsi     230x1517f [
chan receive]:
rbp     0x7fff5fbff4fc
rsp     main.(*InterruptHandler).handleInterrupt0x7fff5fbff4c8(
0xc20800e7c0r8      )
0xa80ec2e7
/Users/pivotal/workspace/diego-release/src/github.com/onsi/ginkgo/ginkgo/interrupt_handler.go:r9      370x22 +
0xbf
r10     created by 0x557de3c5main.NewInterruptHandler

r11     	0x202/Users/pivotal/workspace/diego-release/src/github.com/onsi/ginkgo/ginkgo/interrupt_handler.go
:21r12      +0xa00xf5dc226f500f3


r13     rax     0x19bede5e916b200xe

rbx     r14     0x283fffd60x13b74179236ee800

rcx     r15     0x799eb0
0xc2080a6570rdx
0x283fffd6
rip     rdi     0x40e430x1403

rsi     rflags  0x3a0x202

cs      rbp     0x70x3a

fs      rsp     0x00x799eb0

gs      r8      0x81500000xa80ec225

r9      0x22
r10     0x557de3c5
r11     0x212
r12     0xf5dc226f500f3
r13     0x19bede22f57840
r14     0x13b74178e7d41e00
r15     0xc208038e10
rip     0x3bea3
rflags  0x212
cs      0x7
fs      0x0
gs      0x670000

ruby 2.1.5p273 (system) page in ~/workspace/diego-release/src/github.com/cloudfoundry-incubator/rep/snapshot
± as+ty |master ✗| →
```

**Comment by vito** [comment]
rad
