### ISSUE TITLE
Ginkgo panics to prevent subsequent assertions from running.

### ISSUE THREAD

**Issue by zyjiaobj** [onsi/ginkgo#648]
I was trying a simple test referring to http://onsi.github.io/ginkgo/.
(1) I added a assertion expression `Expect(1).To(Equal(0))` in the `TestBooks` function
```
package books_test

import (
    . "github.com/onsi/ginkgo"
    . "github.com/onsi/gomega"
    "testing"
)

func TestBooks(t *testing.T) {
    RegisterFailHandler(Fail)
    Expect(1).To(Equal(0))
    RunSpecs(t, "Books Suite")
}

var _ = BeforeSuite(func() {
	Expect(1).To(Equal(0))
})
``` 
(2) I run the test, then get a panic error:
```
✗ ginkgo -r ./
--- FAIL: TestBooks (0.00s)
panic: 
Your test failed.
Ginkgo panics to prevent subsequent assertions from running.
Normally Ginkgo rescues this panic so you shouldn't see it.

But, if you make an assertion in a goroutine, Ginkgo can't capture the panic.
To circumvent this, you should call

        defer GinkgoRecover()

at the top of the goroutine that caused this panic.
 [recovered]
        panic: 
Your test failed.
Ginkgo panics to prevent subsequent assertions from running.
Normally Ginkgo rescues this panic so you shouldn't see it.

But, if you make an assertion in a goroutine, Ginkgo can't capture the panic.
To circumvent this, you should call

        defer GinkgoRecover()

at the top of the goroutine that caused this panic.


goroutine 21 [running]:
testing.tRunner.func1(0xc00016c100)
        /usr/local/Cellar/go/1.13.6/libexec/src/testing/testing.go:874 +0x3a3
panic(0x13d6760, 0x14fea00)
        /usr/local/Cellar/go/1.13.6/libexec/src/runtime/panic.go:679 +0x1b2
github.com/onsi/ginkgo.Fail(0xc0000c4090, 0x2b, 0xc0000baa60, 0x1, 0x1)
        /Users/zyjiaobj/abc/golang/pkg/mod/github.com/onsi/ginkgo@v1.10.3/ginkgo_dsl.go:267 +0xc8
github.com/onsi/gomega/internal/assertion.(*Assertion).match(0xc0000c70c0, 0x150df00, 0xc0000ad1a0, 0x1, 0x0, 0x0, 0x0, 0xc0000ad1a0)
        /Users/zyjiaobj/abc/golang/pkg/mod/github.com/onsi/gomega@v1.7.1/internal/assertion/assertion.go:75 +0x1f0
github.com/onsi/gomega/internal/assertion.(*Assertion).To(0xc0000c70c0, 0x150df00, 0xc0000ad1a0, 0x0, 0x0, 0x0, 0x5e5c7d38)
        /Users/zyjiaobj/abc/golang/pkg/mod/github.com/onsi/gomega@v1.7.1/internal/assertion/assertion.go:38 +0xc7
github.ibm.com/coligo/e2e/e2e/ss_test.TestBooks(0xc00016c100)
        /Users/zyjiaobj/Code/coligo/e2e/e2e/ss/a_suite_test.go:11 +0x147
testing.tRunner(0xc00016c100, 0x1496950)
        /usr/local/Cellar/go/1.13.6/libexec/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
        /usr/local/Cellar/go/1.13.6/libexec/src/testing/testing.go:960 +0x350

Ginkgo ran 1 suite in 6.011187477s
Test Suite Failed
```

But if I move assertion expression `Expect(1).To(Equal(0))` from `TestBooks` to `BeforeSuite` function, the result is as expected. 

My question is, is that allowed to use assertion expression in testing test function `TestBooks` ?

**Comment by blgm** [comment]
Hi @zyjiaobj. The `Test<Suite Name>()` function (`TestBooks()` in your case) allows Ginkgo to hook into Go Test, so that running `go test` will also run Ginkgo tests. In general we would not expect there to be Gomega assertions in that function. You are "allowed" to add code there, but it is very rarely done.

In general we see three patterns:
1) Some people write in pure Go Test, not using Ginkgo or Gomega
2) Some people use Gomega assertions (`Expect(...).To(...)`) but do not use Ginkgo. http://onsi.github.io/gomega/#using-gomega-with-golangs-xunit-style-tests
3) Some people use Ginkgo and Gomega together. The assertions are in `It()` or `Specify()` blocks, and Ginkgo catches the `panic()`s and produces useful output. https://onsi.github.io/ginkgo/#adding-specs-to-a-suite

**Comment by onsi** [comment]
Closing due to inactivity
