### ISSUE TITLE
Where can I get ginkgo's design documents

### ISSUE THREAD

**Issue by chenpfeisoo** [onsi/ginkgo#806]
Where can I get ginkgo's design documents ，uml ？

**Comment by onsi** [comment]
hey @chenpfeisoo there aren't any - what are you working on or trying to solve.  perhaps i can help?

**Comment by chenpfeisoo** [comment]
@onsi  Thank you for your warm help
I try to add a description to the ginkgo report, so that I can print the case information completely, including the detailed steps of the case, which is very helpful for other people to read my case. It's a little more elegant than printing step in the code, and it's much more convenient than writing a lot of descriptions in casename. I implemented a simple code a few hours ago

But I also want to have a comprehensive understanding of Ginkgo and see the overall design
![image](https://user-images.githubusercontent.com/18147157/117971222-2db2fc80-b35c-11eb-9999-b1ba906d6c8c.png)

```xml
<?xml version="1.0" encoding="UTF-8"?>
  <testsuite name="mytest_suite" tests="1" failures="0" errors="0" time="0">
      <testcase name="describe:test name:test" classname="mytest_suite" description="&#xA;&#xA;&#xA;&#x9;&#x9;General description: Test whether the new description is available&#xA;        step:1 Create environment&#xA;&#x9;&#x9;step:2 Check the environmen&#xA;&#x9;&#x9;step:3 Perform the test&#xA;&#x9;&#x9;step:4 Destruction environment&#xA;" time="2.9875e-05"></testcase>
  </testsuite>
```

**Comment by onsi** [comment]
hey @chenpfeisoo - thanks for sharing all that detail.  Ginkgo's underlying design is changing with V2 - and I'm trying to make it easier for folks to customize things like this.  There are a couple of changes in V2, for example, that would enable you to support this fairly cleanly I think:

- [Report Entries](https://github.com/onsi/ginkgo/blob/v2/docs/MIGRATING_TO_V2.md#new-report-entries) now allow you to attach arbitrary data to individual spec reports.  These will appear in the generated test reports and you can also control whether the are emitted to the console.

- [Spec Decorations](https://github.com/onsi/ginkgo/blob/v2/docs/MIGRATING_TO_V2.md#spec-decorations) provide a pattern for annotating and configuring individual specs.  I think adding support for new decorators will be a common way to extend Ginkgo.

One thing - I see you added `description` to JUnit's `testcase` - I'm not seeing that in any of the JUnit specs that I've come across.  Is `description` a supported field?

**Comment by chenpfeisoo** [comment]
@onsi Thank you for your reply

V2 see a lot of ability to use, I'm looking forward to it

JUnit adds description as a customized requirement. Our internal report display platform (supports multiple languages) has this field. I realized this ability

**Comment by onsi** [comment]
> internal report display platform

is there a specific product/oss tool you are using for that?  or have you built your own?  i'm asking because I'm trying to learn what people are using in real life to see if there is a new report format I should be supporting.

**Comment by chenpfeisoo** [comment]
This report platform is completely a black box for me. I gave a JUnit report template. I don't know if it is universal
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="6" failures="4" time="3.000">
    <field name="expected" description=" " hidden="true" />
    <field name="steps" description=" " hidden="false" />
    <testsuite tests="5" failures="2" time="3.000" name="TestExampleTestSuite">
        <properties></properties>
        <testcase name="TestExample1" time="0.160" owner="zhangsan" description="Example1" expected="success" steps="1,2,3"></testcase>
        <testcase name="TestExample2" time="0.000" owner="zhangsan" description="Example2">
            <failure message="Failed" type="">math_testify_test.go:35: &#xA;Error Trace:&#x9;math_testify_test.go:35&#xA;Error:      &#x9;Not equal: &#xA;            &#x9;expected: 4&#xA;            &#x9;actual  : 5&#xA;Test:       &#x9;TestExampleTestSuite/TestExample&#xA;suite.go:106: On Case &#xA;    test panicked: CaseDown&#xA;    goroutine 7 [running]:&#xA;    runtime/debug.Stack(0xc000059a10, 0x747be0, 0x818890)&#xA;C:/Go/src/runtime/debug/stack.go:24 +0xae&#xA;    Flerken/testify/suite.failOnPanicWithStatus(0xc0000d0200, 0xc000059f38)&#xA;C:/Users/admin/go/src/Flerken/testify/suite/suite.go:106 +0xa0&#xA;    panic(0x747be0, 0x818890)&#xA;C:/Go/src/runtime/panic.go:513 +0x1c7&#xA;    awesomeProject_test.(*MySuite).TestExample(0xc000004880)&#xA;C:/Users/admin/go/src/awesomeProject/math_testify_test.go:36 +0xc2&#xA;    reflect.Value.call(0xc00037c840, 0xc000006278, 0x13, 0x7c3073, 0x4, 0xc000429f80, 0x1, 0x1, 0xc000429ea8, 0x80, ...)&#xA;C:/Go/src/reflect/value.go:447 +0x45b&#xA;    reflect.Value.Call(0xc00037c840, 0xc000006278, 0x13, 0xc000429f80, 0x1, 0x1, 0x7c2560, 0x71b00d, 0xb)&#xA;C:/Go/src/reflect/value.go:308 +0xab&#xA;    Flerken/testify/suite.Run.func2(0xc0000d0200)&#xA;C:/Users/admin/go/src/Flerken/testify/suite/suite.go:186 +0x320&#xA;    testing.tRunner(0xc0000d0200, 0xc00042e400)&#xA;C:/Go/src/testing/testing.go:827 +0xc6&#xA;    created by testing.(*T).Run&#xA;C:/Go/src/testing/testing.go:878 +0x363</failure>
        </testcase>
        <testcase name="TestExample3" time="0.000" owner="zhangsan" description="Example3">
            <failure message="Failed" type="">math_testify_test.go:39: &#xA;Error Trace:&#x9;math_testify_test.go:39&#xA;Error:      &#x9;Not equal: &#xA;            &#x9;expected: 4&#xA;            &#x9;actual  : 5&#xA;Test:       &#x9;TestExampleTestSuite/TestExample1</failure>
        </testcase>
        <testcase name="TestExample4" time="3.000" owner="zhangsan" description="Example4"></testcase>
        <testcase name="TestExample5" time="0.000" owner="zhangsan" description="Example5">
            <skipped message="math_testify_test.go:54: "></skipped>
        </testcase>
    </testsuite>
    <testsuite tests="2" failures="2" time="0.000" name="TestExample2TestSuite">
        <properties></properties>
        <testcase name="TestExample6" time="0.000" owner="zhangsan" description="Example6">
            <failure message="Failed" type="">suite.go:106: On Setup&#xA;    test panicked: SetupTest123123123123&#xA;    goroutine 22 [running]:&#xA;    runtime/debug.Stack(0xc0002cbdb8, 0x747be0, 0x818880)&#xA;C:/Go/src/runtime/debug/stack.go:24 +0xae&#xA;    Flerken/testify/suite.failOnPanicWithStatus(0xc0003f6000, 0xc0002cbf38)&#xA;C:/Users/admin/go/src/Flerken/testify/suite/suite.go:106 +0xa0&#xA;    panic(0x747be0, 0x818880)&#xA;C:/Go/src/runtime/panic.go:513 +0x1c7&#xA;    awesomeProject_test.(*MySuite2).SetupTest(0xc0003f2060)&#xA;C:/Users/admin/go/src/awesomeProject/math_testify_test.go:30 +0x40&#xA;    Flerken/testify/suite.Run.func2(0xc0003f6000)&#xA;C:/Users/admin/go/src/Flerken/testify/suite/suite.go:168 +0x424&#xA;    testing.tRunner(0xc0003f6000, 0xc0003b9000)&#xA;C:/Go/src/testing/testing.go:827 +0xc6&#xA;    created by testing.(*T).Run&#xA;C:/Go/src/testing/testing.go:878 +0x363</failure>
        </testcase>
        <testcase name="TestExample7" time="0.000" owner="zhangsan" description="Example7">
            <failure message="Failed" type="">suite.go:106: On Setup&#xA;    test panicked: SetupTest123123123123&#xA;    goroutine 23 [running]:&#xA;    runtime/debug.Stack(0xc0002cbdb8, 0x747be0, 0x818880)&#xA;C:/Go/src/runtime/debug/stack.go:24 +0xae&#xA;    Flerken/testify/suite.failOnPanicWithStatus(0xc0003f6200, 0xc0002cbf38)&#xA;C:/Users/admin/go/src/Flerken/testify/suite/suite.go:106 +0xa0&#xA;    panic(0x747be0, 0x818880)&#xA;C:/Go/src/runtime/panic.go:513 +0x1c7&#xA;    awesomeProject_test.(*MySuite2).SetupTest(0xc0003f2060)&#xA;C:/Users/admin/go/src/awesomeProject/math_testify_test.go:30 +0x40&#xA;    Flerken/testify/suite.Run.func2(0xc0003f6200)&#xA;C:/Users/admin/go/src/Flerken/testify/suite/suite.go:168 +0x424&#xA;    testing.tRunner(0xc0003f6200, 0xc0003b9080)&#xA;C:/Go/src/testing/testing.go:827 +0xc6&#xA;    created by testing.(*T).Run&#xA;C:/Go/src/testing/testing.go:878 +0x363</failure>
        </testcase>
    </testsuite>
</testsuites>

```

**Comment by chenpfeisoo** [comment]
@onsi  
I have this problem without parallel, a little confused

redefined: ginkgo.seed

**Comment by onsi** [comment]
can you share more detail?  V1 Ginkgo defines its flags [here](https://github.com/onsi/ginkgo/blob/master/ginkgo_dsl.go#L53) and that `init()` func should only be called once.  I don't think parallel vs not would have an effect.

**Comment by chenpfeisoo** [comment]
```shell
panic: /Users/felixchen/go/src/TKETest/testcase/tcmtest/meshscene/trafficcontrol/managermesh/managermesh.test flag redefined: ginkgo.seed

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc00004e1e0, 0x22eb4d8, 0x2c2d100, 0xc000046d40, 0xb, 0x217bc55, 0x2a)
	/usr/local/go/src/flag/flag.go:871 +0x485
flag.(*FlagSet).Int64Var(...)
	/usr/local/go/src/flag/flag.go:682
git.code.oa.com/felixpfchen/ginkgo/config.Flags(0xc00004e1e0, 0xc000046d38, 0x7, 0xc0000b1601)
	/Users/felixchen/go/pkg/mod/git.code.oa.com/felixpfchen/ginkgo@v0.0.0-20210512093750-ed7d843da834/config/config.go:75 +0x10e
git.code.oa.com/felixpfchen/ginkgo.init.0()
	/Users/felixchen/go/pkg/mod/git.code.oa.com/felixpfchen/ginkgo@v0.0.0-20210512093750-ed7d843da834/ginkgo_dsl.go:54 +0x4b

Ginkgo ran 1 suite in 4.962161913s
Test Suite Failed
```

**Comment by chenpfeisoo** [comment]
@onsi Thank you. I found a problem. There is a reference to GitHub code in our basic library code. Ginkgo of my local warehouse will start again and repeat

**Comment by onsi** [comment]
hey - glad you figured it out!

**Comment by chenpfeisoo** [comment]
Thank you, issue. I'm closed

**Comment by Thor-wl** [comment]
I met the same error at CI recently: 
/home/runner/work/volcano/volcano/test/e2e/schedulingbase/schedulingbase.test flag redefined: ginkgo.seed
panic: /home/runner/work/volcano/volcano/test/e2e/schedulingbase/schedulingbase.test flag redefined: ginkgo.seed
My golang version is 1.16.
