### ISSUE TITLE
Ginkgo 2.0 hangs after running all tests

### ISSUE THREAD

**Issue by blgm** [onsi/ginkgo#871]
I've just tried out Ginkgo 2.0. It's worked perfectly [on one project](https://github.com/cloudfoundry/jsonry/commit/c10c9f2c7ec2c3c9dbea641fee13298cac9e0818), but on a second project, Gingko appeared to hang at the end of the test run. Running with `--progress` didn't reveal anything, so I captured the goroutine state.

You can [try out the code](https://github.com/cloudfoundry-incubator/cloud-service-broker/tree/ginkgo-2.0) just by running `make test`.

Goroutine state:
```
Ran 21 of 21 Specs in 178.672 seconds
SUCCESS! -- 21 Passed | 0 Failed | 0 Pending | 0 Skipped
SIGABRT: abort
PC=0x7fff20345cde m=0 sigcode=0

goroutine 0 [idle]:
runtime.pthread_cond_wait(0x18b9940, 0x18b9900)
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/runtime/sys_darwin.go:444 +0x34
runtime.semasleep(0xffffffffffffffff)
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/runtime/os_darwin.go:66 +0xad
runtime.notesleep(0x18b96f0)
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/runtime/lock_sema.go:182 +0x85
runtime.mPark()
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/runtime/proc.go:1441 +0x2a
runtime.stoplockedm()
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/runtime/proc.go:2602 +0x65
runtime.schedule()
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/runtime/proc.go:3299 +0x3d
runtime.park_m(0xc000115860)
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/runtime/proc.go:3516 +0x14d
runtime.mcall()
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/runtime/asm_amd64.s:307 +0x43

goroutine 1 [chan receive, 85 minutes]:
github.com/onsi/ginkgo/v2/ginkgo/internal.runParallel({{0xc0000be138, 0x11}, {0xc000316230, 0xf}, 0x1, 0x0, {0xc0000fe120, 0x54}, {0x0, 0x0}, ...}, ...)
        /Users/gblue/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.0.0/ginkgo/internal/run.go:211 +0x11df
github.com/onsi/ginkgo/v2/ginkgo/internal.RunCompiledSuite({{0xc0000be138, 0x11}, {0xc000316230, 0xf}, 0x1, 0x0, {0xc0000fe120, 0x54}, {0x0, 0x0}, ...}, ...)
        /Users/gblue/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.0.0/ginkgo/internal/run.go:30 +0x43e
github.com/onsi/ginkgo/v2/ginkgo/run.(*SpecRunner).RunSpecs(0xc000346f30, {0xc00031c420, 0x18e90b8, 0x0}, {0x18e90b8, 0x0, 0x0})
        /Users/gblue/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.0.0/ginkgo/run/run_command.go:151 +0x1176
github.com/onsi/ginkgo/v2/ginkgo/run.BuildRunCommand.func1({0xc00031c420, 0x1, 0x2}, {0x18e90b8, 0x0, 0x0})
        /Users/gblue/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.0.0/ginkgo/run/run_command.go:52 +0x42c
github.com/onsi/ginkgo/v2/ginkgo/command.Command.Run({{0x14f9df3, 0x3}, {{0xc000310000, 0x50, 0x99}, {0x148ab80, 0xc000098450}, {0x18acee0, 0xd, 0xd}, ...}, ...}, ...)
        /Users/gblue/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.0.0/ginkgo/command/command.go:28 +0xa3
github.com/onsi/ginkgo/v2/ginkgo/command.Program.RunAndExit({{0x14fbee3, 0x6}, {0xc0002140a8, 0x14}, {0xc0000d0000, 0x8, 0x8}, {{0x14f9df3, 0x3}, {{0xc000310000, ...}, ...}, ...}, ...}, ...)
        /Users/gblue/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.0.0/ginkgo/command/program.go:113 +0x42a
main.main()
        /Users/gblue/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.0.0/ginkgo/main.go:46 +0x4f8

goroutine 7 [syscall, 87 minutes]:
os/signal.signal_recv()
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/runtime/sigqueue.go:166 +0x28
os/signal.loop()
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/os/signal/signal_unix.go:24 +0x19
created by os/signal.Notify.func1.1
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/os/signal/signal.go:151 +0x2c

goroutine 19 [select, 87 minutes]:
github.com/onsi/ginkgo/v2/internal/interrupt_handler.(*InterruptHandler).registerForInterrupts.func2()
        /Users/gblue/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.0.0/internal/interrupt_handler/interrupt_handler.go:127 +0x11c
created by github.com/onsi/ginkgo/v2/internal/interrupt_handler.(*InterruptHandler).registerForInterrupts
        /Users/gblue/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.0.0/internal/interrupt_handler/interrupt_handler.go:122 +0x1ef

goroutine 34 [select, 87 minutes]:
github.com/onsi/ginkgo/v2/internal/interrupt_handler.(*InterruptHandler).registerForInterrupts.func2()
        /Users/gblue/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.0.0/internal/interrupt_handler/interrupt_handler.go:127 +0x11c
created by github.com/onsi/ginkgo/v2/internal/interrupt_handler.(*InterruptHandler).registerForInterrupts
        /Users/gblue/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.0.0/internal/interrupt_handler/interrupt_handler.go:122 +0x1ef

goroutine 44 [IO wait, 87 minutes]:
internal/poll.runtime_pollWait(0x1f48f18, 0x72)
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc0000a6400, 0x4, 0x0)
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc0000a6400)
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/internal/poll/fd_unix.go:402 +0x22c
net.(*netFD).accept(0xc0000a6400)
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/net/fd_unix.go:173 +0x35
net.(*TCPListener).accept(0xc0000a82b8)
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/net/tcpsock_posix.go:140 +0x28
net.(*TCPListener).Accept(0xc0000a82b8)
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/net/tcpsock.go:262 +0x3d
net/http.(*Server).Serve(0xc000376000, {0x15ae960, 0xc0000a82b8})
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/net/http/server.go:3002 +0x394
created by github.com/onsi/ginkgo/v2/internal/parallel_support.(*RPCServer).Start
        /Users/gblue/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.0.0/internal/parallel_support/rpc_server.go:48 +0x10f

goroutine 45 [IO wait, 85 minutes]:
internal/poll.runtime_pollWait(0x1f48e30, 0x72)
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc000097b60, 0xc0001ee605, 0x1)
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000097b60, {0xc0001ee605, 0x5fb, 0x5fb})
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/internal/poll/fd_unix.go:167 +0x25a
os.(*File).read(...)
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/os/file_posix.go:32
os.(*File).Read(0xc0000a0300, {0xc0001ee605, 0x0, 0xc00031f6a0})
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/os/file.go:119 +0x5e
bytes.(*Buffer).ReadFrom(0xc0000997a0, {0x15a5280, 0xc0000a0300})
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/bytes/buffer.go:204 +0x98
io.copyBuffer({0x15a4740, 0xc0000997a0}, {0x15a5280, 0xc0000a0300}, {0x0, 0x0, 0x0})
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/io/io.go:409 +0x14b
io.Copy(...)
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/io/io.go:382
os/exec.(*Cmd).writerDescriptor.func1()
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/os/exec/exec.go:311 +0x3a
os/exec.(*Cmd).Start.func1(0x0)
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/os/exec/exec.go:441 +0x25
created by os/exec.(*Cmd).Start
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/os/exec/exec.go:440 +0x80d

goroutine 46 [chan receive, 85 minutes]:
os/exec.(*Cmd).Wait(0xc000360160)
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/os/exec/exec.go:515 +0x188
github.com/onsi/ginkgo/v2/ginkgo/internal.runParallel.func2()
        /Users/gblue/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.0.0/ginkgo/internal/run.go:200 +0x2f
created by github.com/onsi/ginkgo/v2/ginkgo/internal.runParallel
        /Users/gblue/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.0.0/ginkgo/internal/run.go:199 +0x4bc

goroutine 57 [IO wait, 85 minutes]:
internal/poll.runtime_pollWait(0x1f488c0, 0x72)
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc000438480, 0xc0003ce005, 0x1)
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000438480, {0xc0003ce005, 0x5fb, 0x5fb})
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/internal/poll/fd_unix.go:167 +0x25a
os.(*File).read(...)
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/os/file_posix.go:32
os.(*File).Read(0xc0000a03c0, {0xc0003ce005, 0x0, 0xc0004416a0})
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/os/file.go:119 +0x5e
bytes.(*Buffer).ReadFrom(0xc0000999e0, {0x15a5280, 0xc0000a03c0})
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/bytes/buffer.go:204 +0x98
io.copyBuffer({0x15a4740, 0xc0000999e0}, {0x15a5280, 0xc0000a03c0}, {0x0, 0x0, 0x0})
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/io/io.go:409 +0x14b
io.Copy(...)
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/io/io.go:382
os/exec.(*Cmd).writerDescriptor.func1()
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/os/exec/exec.go:311 +0x3a
os/exec.(*Cmd).Start.func1(0x0)
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/os/exec/exec.go:441 +0x25
created by os/exec.(*Cmd).Start
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/os/exec/exec.go:440 +0x80d

goroutine 58 [chan receive, 85 minutes]:
os/exec.(*Cmd).Wait(0xc0003609a0)
        /Users/gblue/.gimme/versions/go1.17.4.darwin.amd64/src/os/exec/exec.go:515 +0x188
github.com/onsi/ginkgo/v2/ginkgo/internal.runParallel.func2()
        /Users/gblue/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.0.0/ginkgo/internal/run.go:200 +0x2f
created by github.com/onsi/ginkgo/v2/ginkgo/internal.runParallel
        /Users/gblue/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.0.0/ginkgo/internal/run.go:199 +0x4bc

rax    0x104
rbx    0x3cb7e00
rcx    0x7ffeefbfedb8
rdx    0x1d00
rdi    0x18b9940
rsi    0x250100002600
rbp    0x7ffeefbfee60
rsp    0x7ffeefbfedb8
r8     0x0
r9     0xa0
r10    0x0
r11    0x246
r12    0x18b9900
r13    0x16
r14    0x250100002600
r15    0x1d00
rip    0x7fff20345cde
rflags 0x247
cs     0x7
fs     0x0
gs     0x0
exit status 2
make: *** [test-integration] Error 1
```

**Comment by blgm** [comment]
Thanks for your response @onsi.

There don't seem to be any child processes:
```
$ pstree 80460
-+- 80460 gblue go run github.com/onsi/ginkgo/v2/ginkgo -p integrationtest/...
 \--- 80476 gblue /var/folders/4k/flm0mkqd5s1dtqdt66byv3rr0000gn/T/go-build453826302/b001/exe/ginkgo -p integrationtest/...
```

Adding `--output-interceptor-mode=none` made Ginkgo complete as expected.

I decided to dig into exactly which test was causing the issue, and I found that focusing on [this one](https://github.com/cloudfoundry-incubator/cloud-service-broker/blob/ec73d0faceb755126ea606fe9dd9b8ab00fd5912/integrationtest/database_encryption_test.go#L598) was sufficient to cause the issue, and there was missing a `session.Terminate()`. By adding a `session.Termiate()` the issue is resolved.

I'm curious as to what was going on. There was a missing `session.Terminate()` but I didn't see a child process. And the issue was also resolved by adding `--output-interceptor-mode=none`. Nevertheless, I'm happy for this to be closed now.

**Comment by onsi** [comment]
I'm also not seeing the actual test binaries running in your `pstree`... strange.  

I'm glad it's resolved - and I think the bits I can add to catch when this happens and notify the user will help others get to resolution faster as well.... but these hanging processes because of subtleties in how stdout/stderr are piped in linux sure are annoying :/

**Comment by blgm** [comment]
I tried this again and was able to find the unterminated program using `ps`:
```
  501 94297     1   0 10:00am ttys003    0:00.50 /var/folders/4k/flm0mkqd5s1dtqdt66byv3rr0000gn/T/gexec_artifacts1921810216/g3188867058/cloud-service-broker serve
```
As you can see the PPID is `1`. So what I think is going on is that the test program spawned `cloud-service-broker` (the test subject) and then the test program exited (I can't find it in the `ps` listing), so `cloud-service-broker` was adopted by `init` (or `launchd` on a Mac), but STDOUT and STDERR were still connected to `ginkgo`.

I'm going to close this as we don't have an issue any more.
