### ISSUE TITLE
Panic with proto file already registered after module dependency update

### ISSUE THREAD

**Issue by fernandesnikhil** [onsi/ginkgo#972]
I recently updated the modules on a project I'm working on. Prior to the update I was able to run my Ginkgo tests with 
```ginkgo -r```

After the update I get the following error
```
ginkgo -r 
panic: proto: file "extensions/extension.proto" is already registered
        previously from: "github.com/googleapis/gnostic/extensions"
        currently from:  "github.com/google/gnostic/extensions"
See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict


goroutine 1 [running]:
google.golang.org/protobuf/reflect/protoregistry.glob..func1({0x16a1660, 0x16f6240}, {0x16a1660, 0xc00044c170})
        /home/nikhil/go/pkg/mod/google.golang.org/protobuf@v1.28.0/reflect/protoregistry/registry.go:54 +0x1f4
google.golang.org/protobuf/reflect/protoregistry.(*Files).RegisterFile(0xc0003c5b90, {0x16f6240, 0xc0004321c0})
        /home/nikhil/go/pkg/mod/google.golang.org/protobuf@v1.28.0/reflect/protoregistry/registry.go:128 +0x399
google.golang.org/protobuf/internal/filedesc.Builder.Build({{0x12bbec0, 0x24}, {0x20c3a40, 0x282, 0x282}, 0x0, 0x4, 0x0, 0x0, {0x16b0540, ...}, ...})
        /home/nikhil/go/pkg/mod/google.golang.org/protobuf@v1.28.0/internal/filedesc/build.go:113 +0x1d6
google.golang.org/protobuf/internal/filetype.Builder.Build({{{0x12bbec0, 0x24}, {0x20c3a40, 0x282, 0x282}, 0x0, 0x4, 0x0, 0x0, {0x0, ...}, ...}, ...})
        /home/nikhil/go/pkg/mod/google.golang.org/protobuf@v1.28.0/internal/filetype/build.go:139 +0x198
github.com/google/gnostic/extensions.file_extensions_extension_proto_init()
        /home/nikhil/go/pkg/mod/github.com/google/gnostic@v0.6.9/extensions/extension.pb.go:456 +0x198
github.com/google/gnostic/extensions.init.0()
        /home/nikhil/go/pkg/mod/github.com/google/gnostic@v0.6.9/extensions/extension.pb.go:388 +0x17

Ginkgo ran 1 suite in 1.178355963s

Test Suite Failed
```

The go module update changed the following
```
go get -u
go: downloading sigs.k8s.io/controller-runtime v0.11.2
go: downloading k8s.io/klog/v2 v2.60.1
go: downloading golang.org/x/sys v0.0.0-20220429121018-84afa8d3f7b3
go: downloading golang.org/x/net v0.0.0-20220425223048-2871e0cb64e4
go: downloading github.com/go-logr/logr v1.2.3
go: downloading sigs.k8s.io/structured-merge-diff v1.0.2
go: downloading github.com/google/go-cmp v0.5.8
go: downloading golang.org/x/time v0.0.0-20220411224347-583f2d630306
go: downloading golang.org/x/term v0.0.0-20220411215600-e5f449aeb171
go: downloading golang.org/x/oauth2 v0.0.0-20220411215720-9780585627b5
go: downloading k8s.io/kube-openapi v0.0.0-20220413171646-5e7f5fdc6da6
go: downloading github.com/googleapis/gnostic v0.6.9
go: downloading google.golang.org/protobuf v1.28.0
go: downloading github.com/Sanyaku/paas-cd-operator v0.0.0-20220429213736-153481289b92
go: downloading knative.dev/pkg v0.0.0-20220428192552-5c8cc3c9efd3
go: downloading gomodules.xyz/jsonpatch v1.0.1
go: downloading github.com/google/gnostic v0.5.7-v3refs
go: downloading github.com/google/gnostic v0.6.9
go get: upgraded github.com/Sanyaku/paas-cd-operator v0.0.0-20220427181906-2fe1b4746d0e => v0.0.0-20220429213736-153481289b92
go get: upgraded github.com/evanphx/json-patch v4.12.0+incompatible => v5.6.0+incompatible
go get: upgraded github.com/go-logr/logr v1.2.2 => v1.2.3
go get: added github.com/google/gnostic v0.6.9
go get: upgraded github.com/google/go-cmp v0.5.7 => v0.5.8
go get: upgraded golang.org/x/net v0.0.0-20220127200216-cd36cc0744dd => v0.0.0-20220425223048-2871e0cb64e4
go get: upgraded golang.org/x/oauth2 v0.0.0-20211104180415-d3ed0bb246c8 => v0.0.0-20220411215720-9780585627b5
go get: upgraded golang.org/x/sys v0.0.0-20220114195835-da31bd327af9 => v0.0.0-20220429121018-84afa8d3f7b3
go get: upgraded golang.org/x/term v0.0.0-20210927222741-03fcf44c2211 => v0.0.0-20220411215600-e5f449aeb171
go get: upgraded golang.org/x/time v0.0.0-20210723032227-1f47c861a9ac => v0.0.0-20220411224347-583f2d630306
go get: upgraded google.golang.org/protobuf v1.27.1 => v1.28.0
go get: upgraded k8s.io/klog/v2 v2.40.1 => v2.60.1
go get: upgraded k8s.io/kube-openapi v0.0.0-20220124234850-424119656bbf => v0.0.0-20220413171646-5e7f5fdc6da6
go get: upgraded k8s.io/utils v0.0.0-20211208161948-7d6a63dca704 => v0.0.0-20220210201930-3a6ce19ff2f9
go get: upgraded knative.dev/pkg v0.0.0-20220129160148-ca64d3b3ea8c => v0.0.0-20220428192552-5c8cc3c9efd3
go get: upgraded sigs.k8s.io/controller-runtime v0.11.0 => v0.11.2
go get: upgraded sigs.k8s.io/json v0.0.0-20211020170558-c049b76a60c6 => v0.0.0-20211208200746-9f7c6b3444d2
```

I'm just getting into Go programming I don't fully understand how I could resolve this. Could someone help me understand what went wrong when I updated my module dependencies and how I can solve this?

**Comment by fernandesnikhil** [comment]
I undid the `go get -u` and did a more targetted update on a single dependency that I wanted to get the latest version of and it's working now.
